version: '3.4'

services:
  mktfy.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "35000:80"
      - "35001:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  mktfy.auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  mktfy.db:
    restart: on-failure
    image: "mdillon/postgis:latest"
    container_name: "MKTFY.db"
    environment:
        - POSTGRES_USER=devuser
        - POSTGRES_DB=MKTFYdB
        - POSTGRESS_PASSWORD=devpassword
    volumes:
        - MKTFY-db:/var/lib/postgerssql/data
    ports:
        - "36000:5432"

volumes:
    MKTFY-db:
