version: '3.4'

services:
  mktfy.api:
    container_name: "MFTFY.api" 
    environment:
      - ConnectionStrings__DefaultConnection=Server=MKTFY.db;Database=MKTFYdevdB;User Id=devuser;password=devpassword
      - Identity__Authority=http://MFTFY.auth

    ports:
      - "35000:80"
      - "35001:443"
    depends_on: 
      - "MKTFY.db"
  mktfy.auth:
    container_name: "MFTFY.auth"
    environment:
      - ConnectionStrings__DefaultConnection=Server=MKTFY.db;Database=MKTFYdevdB;User Id=devuser;password=devpassword
      - Identity__Authority=http://MFTFY.auth
    ports:
      - "34000:80"
      - "34001:443"
  MKTFY.db:
    restart: on-failure
    image: "mdillon/postgis:latest"
    container_name: "MKTFY.db"
    environment:
        - POSTGRES_USER=devuser
        - POSTGRES_DB=MKTFYdevdB
        - POSTGRESS_PASSWORD=devpassword
    volumes:
        - MKTFY-db:/var/lib/postgerssql/data
    ports:
        - "36000:5432"

volumes:
    MKTFY-db:
